# ADD AT THE BOTTOM BEFORE }

#ifdef ENABLE_BIOLOG_SYSTEM
	PyModule_AddIntConstant(poModule, "BIOLOG_MANAGER_OPEN", CG_BIOLOG_MANAGER_OPEN);
	PyModule_AddIntConstant(poModule, "BIOLOG_MANAGER_SEND", CG_BIOLOG_MANAGER_SEND);
	PyModule_AddIntConstant(poModule, "BIOLOG_MANAGER_TIMER", CG_BIOLOG_MANAGER_TIMER);
#endif